import LegalPage from "@/components/marketing/LegalPage";

export const metadata = {
  title: "Privacy Policy",
  description: "Privacy Policy draft for the Blackbird website and scoring app.",
  robots: { index: false, follow: false },
};

export default function PrivacyPage() {
  return (
    <LegalPage title="Privacy Policy" prepared="Prepared September 23, 2026 and updated September 25, 2026 to cover Blackbird AI and coaching features. Contact details and operating policies must be confirmed before public release.">
      <p className="mk-legal-intro">This draft describes how information is handled by the Blackbird product website and the separate Blackbird Dart Scoring System, presented by Sinitiere Labs.</p>
<h2>Information You Provide</h2><p>The scoring app uses email and password authentication. Your account may include a display name, player handle, profile description, home bar or town, profile colour, cover and name tag, and player preferences such as gameplay, strategy hint, and answer style settings. The app records game results, opponents, scores, dart-by-dart logs, performance statistics, practice activity, and the players you follow.</p>
<h2>Information Created as You Use the App</h2><p>The app records the days you open it and when you complete parts of your profile, which power streak and profile achievements. If you use training plans, the plans you create or accept and your progress through them are saved to your account. Strategy hints, Alter Ego, and the Merlin card are calculated from your own saved games inside Blackbird; they do not send your data to an AI provider.</p>
<h2>Blackbird AI</h2><p>When you ask Blackbird AI a question, use an Ask AI shortcut, request a match summary, or ask Merlin to draft a training plan, Blackbird sends a request to a third-party AI model provider (currently OpenAI) to write the answer. That request includes your question, recent messages from the same conversation, and the Blackbird game data needed to answer it: your own games and statistics and, when you ask about other players, their shared results and statistics. The provider processes this information under its own terms and data policies. Please don’t include sensitive personal information in your questions.</p>
<p>Your Blackbird AI conversation is kept in your browser on the device you used, not in Blackbird’s database. For each request, Blackbird’s servers keep an operational record: the type of request, the model used, token counts, duration, and whether it succeeded. They also keep a daily count used for the 50-request daily limit. These records do not include your question, the answer, or the game data that was sent.</p>
<h2>Website Previews and Background Effects</h2><p>The example scores, conversations, and statistics on this website are demonstrations. The product previews, animated counters, and cursor-responsive dot grid run in your browser. This website’s current application code does not submit mouse coordinates or preview interactions to a server and does not include advertising pixels or marketing analytics.</p>
<h2>How Information Is Used</h2><p>Account and game information supports sign-in, player profiles, scoring, saved results, practice history, standings, achievements, matchup predictions, training plans, and AI coaching answers. TV pairing uses a room code to share a live scoreboard with connected screens. The Blackbird operator can view account lists and usage figures, such as sign-ups, activity, games played, and AI request counts and estimated costs, to run, support, and protect the service. The website’s hosting service may process account and technical connection information to deliver and protect the site.</p>
<h2>Player and Scoreboard Visibility</h2><p>The app includes shared player profiles and competitive statistics. Other signed-in players may see player names, handles, profile details, results, standings, achievements, and head-to-head records, and may ask Blackbird AI about those shared results. A screen paired to your TV room can display live scores and match results. A player card you export or share shows what is on the card to anyone you send it to. Avoid putting sensitive personal information into a player profile, and share TV room codes only with people you intend to include.</p>
<h2>Service Providers and Browser Storage</h2><p>The app’s documented architecture uses Supabase for authentication, data storage, and real-time scoreboard updates, Vercel for application hosting, and a third-party AI model provider (currently OpenAI) for Blackbird AI answers. The app uses browser storage for features such as saved sign-in state, preferences, recovery of an in-progress game, games saved while offline until they sync, your Blackbird AI conversation, cached match summaries, TV display settings, and the files that let the installed app open without a connection. Hosting providers may maintain their own security and operational logs. This website does not add advertising cookies through its application code.</p>
<h2>Retention, Requests, and Your Choices</h2><p>You can edit supported profile fields and turn strategy hints off through the app, choose whether to use Blackbird AI, and manage browser storage through your device settings. Clearing browser storage removes your saved Blackbird AI conversation from that device, and any games still waiting to sync. It does not itself delete account information or saved game history. AI usage records, training plans, and app activity records are linked to your account and are removed if the account is deleted. The final policy must identify the privacy contact, retention periods, account deletion process, and any applicable request or appeal procedures before public release.</p>
<h2>Security and Children’s Privacy</h2><p>Authentication and access controls are part of the app’s design. No online service can guarantee absolute security. The final policy must confirm the intended age range and the process for handling information submitted by children before accounts are offered publicly.</p>
<h2>Contact and Policy Updates</h2><p>Sinitiere Labs’ privacy contact and the policy’s effective date have not yet been confirmed. They will be added before this draft becomes an effective policy. Any change of AI provider, and any future collection of analytics, advertising data, payment information, or optical-scoring images, must be reviewed and reflected in the policy before that collection begins.</p>
    </LegalPage>
  );
}
