/**
 * Offline conformance: replay fixture event streams through scoring-core
 * and require the exact perPlayer stats the REAL app recorded when the
 * same games were played through its UI. Fixtures are generated by the
 * Playwright capture harness (see ARCHITECTURE.md §14); regenerate them
 * whenever scoring rules intentionally change.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { createGame, applyGameEvent, deriveCompletedResult } from "../packages/scoring-core/index.js";

const { scenarios } = JSON.parse(readFileSync(new URL("./fixtures/conformance.json", import.meta.url), "utf8"));

for (const s of scenarios) {
  test(`conformance: ${s.name}`, () => {
    let state = createGame({ gameType: s.gameType, players: s.players, config: s.config });
    for (const e of s.events) state = applyGameEvent(state, e);
    const match = deriveCompletedResult(state, "fixture");
    assert.ok(match, "game must complete");
    assert.equal(match.winner, s.expected.winner);
    for (const player of s.players) {
      // the app records more than scoring-core derives (stats v2 visits,
      // timings); compare the keys the core emits
      const got = match.perPlayer[player];
      const want = {};
      for (const k of Object.keys(got)) want[k] = s.expected.perPlayer[player][k];
      assert.deepEqual(got, want, `stats for ${player}`);
    }
  });
}
