/** The nine game modes as the marketing page describes them. */
export const GAMES = [
  { id: "X01", eyebrow: "THE CLASSIC COUNTDOWN", title: "One Perfect Finish.", copy: "Start at 301, 501, or 701 and work your way to zero. Choose double-out and play a single leg or a best-of match.", how: "Every visit updates your average and checkout stats. Strategy hints can suggest a finishing route as you get close, and a bot can step in when you’re short a player.", players: "1+ players · Bots available" },
  { id: "Cricket", eyebrow: "CLOSE THE NUMBERS", title: "Make Your Marks.", copy: "Play Standard, Cutthroat, or No-score Cricket. Follow every close, every point, and your live marks per round.", how: "Close 15 through 20 and the bull by hitting each three times, and score on numbers your opponents haven’t closed. Cutthroat flips the points onto your rivals.", players: "1+ players · Bots available" },
  { id: "Baseball", eyebrow: "NINE INNINGS. YOUR BOARD.", title: "Step Up to the Line.", copy: "Bring Baseball to the dartboard. Score runs across nine innings, with extra innings to break a tie.", how: "In inning one you aim at the 1, in inning two the 2, and so on. A single, double, or triple scores one, two, or three runs. Most runs after nine innings wins.", players: "1+ players · Bots available" },
  { id: "Around the Clock", eyebrow: "ONE NUMBER AT A TIME", title: "Work Your Way Around.", copy: "Take on the board in sequence. Blackbird tracks your targets hit and darts thrown as you make your way around.", how: "Hit 1 through 20, then the bull, in order. Any single, double, or triple counts, and the first to finish wins.", players: "1+ players" },
  { id: "Killer", eyebrow: "EVERY LIFE COUNTS", title: "Keep Yourself in the Game.", copy: "Claim your number, become a killer, and take on the other players. Blackbird keeps track of the lives.", how: "Everyone gets a random number. Hit your own double to become a killer, then take lives with your rivals’ doubles. Play with 3, 5, or 7 lives.", players: "2+ players" },
  { id: "Shanghai", eyebrow: "A DIFFERENT TARGET EACH ROUND", title: "Find Your Shanghai.", copy: "Build your score round by round, or hit the single, double, and triple of the round’s number for a Shanghai.", how: "Seven rounds on sequential targets, in Beginner (1–7) or Advanced (15–20 and the bull). Only darts on the round’s target score.", players: "1+ players" },
  { id: "Halve It", eyebrow: "HIT THE TARGET. KEEP YOUR SCORE.", title: "Make the Next Round Count.", copy: "Work through the target rounds and protect your total. Miss a round’s target and your score is halved.", how: "Nine rounds of fixed targets: 20, 19, 18, any double, 17, 16, 15, any triple, and the bull. Score nothing in a round and your total is cut in half.", players: "1+ players" },
  { id: "Gotcha", eyebrow: "THE CHASE IS ON", title: "Catch Your Competition.", copy: "Build toward the target score and reset a rival by landing on their total. Blackbird tracks the resets and the race.", how: "Race to exactly 301 or 501. Go over and you bust. Land on a rival’s exact score and send them back to zero.", players: "2+ players" },
  { id: "Tic-Tac-Toe", eyebrow: "THREE IN A ROW", title: "Play the Board Differently.", copy: "Turn the familiar grid into a darts challenge. Claim squares and build a winning line while Blackbird keeps track.", how: "A 3×3 grid of numbers from 20 down to 12. Hit a square to claim it, hit your rival’s to cancel it, and get three in a row.", players: "2 players" },
];
